# ============================================================
# uninstall.ps1
# Folder Integrity Monitoring  Uninstall Script
# Generated by SilentHook Deception Engine
# ============================================================
# Run once as Administrator:
#   powershell.exe -ExecutionPolicy Bypass -File .\uninstall.ps1
# ============================================================

$baitId      = "TOKEN"
$FolderPath  = "MONITORED_PATH"
$TaskName    = "Watcher_${baitId}"
$WatcherPath = "C:\watcher\$baitId.ps1"

Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "  SilentHook FIM Uninstall                           " -ForegroundColor Cyan
Write-Host "======================================================" -ForegroundColor Cyan

# Stoping and remove scheduled task
Write-Host "[*] Removing scheduled task: $TaskName" -ForegroundColor Cyan
$task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($task) {
    & schtasks.exe /End /TN $TaskName | Out-Null
    & schtasks.exe /Delete /TN $TaskName /F | Out-Null
    Write-Host "[+] Scheduled task removed" -ForegroundColor Green
} else {
    Write-Host "[-] Scheduled task not found skipping" -ForegroundColor Yellow
}

# Removing watcher script
Write-Host "[*] Removing watcher script: $WatcherPath" -ForegroundColor Cyan
if (Test-Path $WatcherPath) {
    & attrib -h -s $WatcherPath
    Remove-Item $WatcherPath -Force
    Write-Host "[+] Watcher script removed" -ForegroundColor Green
} else {
    Write-Host "[-] Watcher script not found skipping" -ForegroundColor Yellow
}

# STEP 3 — Remove watcher folder if empty
$watcherDir = "C:\watcher"
if (Test-Path $watcherDir) {
    $remaining = Get-ChildItem $watcherDir -ErrorAction SilentlyContinue
    if (-not $remaining) {
        Remove-Item $watcherDir -Force
        Write-Host "[+] Watcher folder removed" -ForegroundColor Green
    } else {
        Write-Host "[!] Watcher folder not empty other baits may still be active" -ForegroundColor Yellow
    }
}

# Removing	 audit rule from folder
Write-Host "[*] Removing audit rule from: $FolderPath" -ForegroundColor Cyan
if (Test-Path $FolderPath) {
    try {
        $acl = Get-Acl $FolderPath
        $auditRule = New-Object System.Security.AccessControl.FileSystemAuditRule(
            "Everyone", "FullControl", "ContainerInherit,ObjectInherit", "None", "Success"
        )
        $acl.RemoveAuditRule($auditRule) | Out-Null
        Set-Acl $FolderPath $acl
        Write-Host "[+] Audit rule removed from folder" -ForegroundColor Green
    } catch {
        Write-Host "[-] Could not remove audit rule: $_" -ForegroundColor Red
    }
} else {
    Write-Host "[-] Folder not found  skipping audit rule removal" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "======================================================" -ForegroundColor Green
Write-Host "  Uninstall Complete!                                " -ForegroundColor Green
Write-Host "  Task     : $TaskName removed                       " -ForegroundColor Green
Write-Host "  Script   : $WatcherPath removed                    " -ForegroundColor Green
Write-Host "  Folder   : $FolderPath audit rule removed          " -ForegroundColor Green
Write-Host "======================================================" -ForegroundColor Green