# ============================================================
# deploy.ps1
# Folder Integrity Monitoring  Script
# Generated by Deception Based Defence Platform
# ============================================================
# Run once as Administrator:
#   powershell.exe -ExecutionPolicy Bypass -File .\deploy.ps1
# Place watcher.ps1 in the same folder as deploy.ps1
# ============================================================

$baitId      = "TOKEN"
$FolderPath  = "MONITORED_PATH"
$CallbackURL = "CALLBACK_URL" 


$FolderName  = Split-Path $FolderPath -Leaf
$TaskName    = "Watcher_${baitId}" # i.e Watcher_ae99ed54340fb22f : Bg Process Name
$WatcherPath = "C:\watcher\$baitId.ps1"
$WatcherSrc  = "$PSScriptRoot\watcher.ps1"


# FUNCTION 1 - Enable Audit Policy
function Enable-AuditPolicy {
    Write-Host "[*] Enabling File System audit policy..." -ForegroundColor Cyan
    
    & auditpol /set /subcategory:"File System" /success:enable /failure:enable | Out-Null
    
    $check = & auditpol /get /subcategory:"File System"
    
    if ($check -match "Success") {
        Write-Host "[+] Audit policy enabled" -ForegroundColor Green
    } else {
        Write-Host "[!] Audit policy may not have applied" -ForegroundColor Yellow
    }
}


# FUNCTION 2 - Apply Folder Audit Rule
function Set-FolderAuditRule {
    Write-Host "[*] Applying audit rule to folder..." -ForegroundColor Cyan

    if (-not (Test-Path $FolderPath)) {
        Write-Host "[-] Folder not found: $FolderPath" -ForegroundColor Red
        Write-Host "[-] Create the folder first then re-run." -ForegroundColor Red
        exit 1
    }

    $acl = Get-Acl $FolderPath
    $auditRule = New-Object System.Security.AccessControl.FileSystemAuditRule(
        "Everyone", "FullControl", "ContainerInherit,ObjectInherit", "None", "Success"
    )
    $acl.AddAuditRule($auditRule)
    Set-Acl $FolderPath $acl
    Write-Host "[+] Audit rule applied to: $FolderPath" -ForegroundColor Green
}


# FUNCTION 3 - Install Persistence
function Install-Persistence {
    Write-Host "[*] Installing persistent watcher..." -ForegroundColor Cyan

    # Check watcher.ps1 is available next to deploy.ps1
    if (-not (Test-Path $WatcherSrc)) {
        Write-Host "[-] watcher.ps1 not found at: $WatcherSrc" -ForegroundColor Red
        Write-Host "[-] Place watcher.ps1 in the same folder as deploy.ps1" -ForegroundColor Red
        exit 1
    }

    # Create destination folder for watcher ps script
    if (-not (Test-Path (Split-Path $WatcherPath))) {
        New-Item -ItemType Directory -Path (Split-Path $WatcherPath) -Force | Out-Null
    }

    # Remove hidden/system attributes if file exists
    if (Test-Path $WatcherPath) { & attrib -h -s $WatcherPath }

    # Read watcher template and inject FolderName and CallbackURL
    $script = Get-Content $WatcherSrc -Raw
    $script = $script -replace 'FOLDER_NAME',  $FolderName
    $script = $script -replace 'URL_CALLBACK', $CallbackURL
    $script | Out-File -FilePath $WatcherPath -Encoding UTF8 -Force

    & attrib +h +s $WatcherPath
    Write-Host "[+] Watcher script deployed to: $WatcherPath" -ForegroundColor Green

    # Install as silent scheduled task - compatible with all Windows versions
    & schtasks.exe /Create /TN $TaskName /TR "powershell.exe -windowstyle hidden -ExecutionPolicy Bypass -File `"$WatcherPath`"" /SC ONSTART /RU SYSTEM /RL HIGHEST /F | Out-Null
    & schtasks.exe /Run /TN $TaskName

    Write-Host "[+] Scheduled task installed: $TaskName" -ForegroundColor Green
    Write-Host "[+] Watcher started immediately" -ForegroundColor Green
}

# FUNCTION 4 - Verify Deployment
function Test-Deployment {
    Write-Host ""
    Write-Host "[*] Verifying deployment..." -ForegroundColor Cyan

    $audit = & auditpol /get /subcategory:"File System"
    if ($audit -match "Success") {
        Write-Host "[+] Audit policy     : ENABLED" -ForegroundColor Green
    } else {
        Write-Host "[-] Audit policy     : FAILED" -ForegroundColor Red
    }

    if (Test-Path $FolderPath) {
        Write-Host "[+] Bait folder      : EXISTS" -ForegroundColor Green
    } else {
        Write-Host "[-] Bait folder      : MISSING" -ForegroundColor Red
    }

    if (Test-Path $WatcherPath) {
        Write-Host "[+] Watcher script   : EXISTS" -ForegroundColor Green
    } else {
        Write-Host "[-] Watcher script   : MISSING" -ForegroundColor Red
    }

    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($task) {
        Write-Host "[+] Scheduled task   : $($task.State)" -ForegroundColor Green
    } else {
        Write-Host "[-] Scheduled task   : NOT FOUND" -ForegroundColor Red
    }
}


# MAIN
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "  Bait Folder Token Deployment Script                 " -ForegroundColor Cyan
Write-Host "  Deception Based Defence Platform                    " -ForegroundColor Cyan
Write-Host "======================================================" -ForegroundColor Cyan

Enable-AuditPolicy
Set-FolderAuditRule
Install-Persistence
Test-Deployment

Write-Host ""
Write-Host "======================================================" -ForegroundColor Green
Write-Host "  Deployment Complete!                                " -ForegroundColor Green
Write-Host "  Folder   : $FolderPath                             " -ForegroundColor Green
Write-Host "  Callback : $CallbackURL                            " -ForegroundColor Green
Write-Host "  Task     : $TaskName                               " -ForegroundColor Green
Write-Host "======================================================" -ForegroundColor Green
